version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd client
      - npm ci
      
  build:
    commands:
      - echo "Building React application..."
      - npm run build
      
  post_build:
    commands:
      - echo "Deploying to S3..."
      - |
        aws s3 sync dist/ s3://${S3_BUCKET}/ \
          --delete \
          --cache-control "public, max-age=31536000, immutable" \
          --exclude "*.html" \
          --exclude "*.json"
      - |
        aws s3 cp dist/index.html s3://${S3_BUCKET}/index.html \
          --cache-control "no-cache, no-store, must-revalidate" \
          --content-type "text/html"
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DIST_ID} --paths "/*"
      - echo "✅ Frontend deployment completed!"

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - 'node_modules/**/*'