version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/apps/renting-manager-kiro/server

hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: ubuntu

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: ubuntu