version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - cd server
      - npm ci
      
  build:
    commands:
      - echo "Building application..."
      - npm run build
      - echo "Generating Prisma Client..."
      - npx prisma generate
      
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - 'dist/**/*'
    - 'node_modules/**/*'
    - 'prisma/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
  base-directory: server
  name: BackendBuildArtifact

cache:
  paths:
    - 'node_modules/**/*'